name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: yarn
      - run: yarn build
      - run: yarn deploy
        env:
          MINI_APPS_ACCESS_TOKEN: ${{ secrets.MINI_APPS_ACCESS_TOKEN }}
          MINI_APPS_ENVIRONMENT: 'production'
      - uses: cteamdev/vk-actions-notify@beta8
        with:
          token: ${{ secrets.VK_TOKEN }}
          peer_id: ${{ secrets.VK_PEER_ID }}
